prompt --application/pages/page_00050
begin
--   Manifest
--     PAGE: 00050
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.1'
,p_default_workspace_id=>69515084060328672
,p_default_application_id=>105
,p_default_id_offset=>0
,p_default_owner=>'WKSP_SRVDEV'
);
wwv_flow_imp_page.create_page(
 p_id=>50
,p_name=>unistr('Usu\00E1rio lista')
,p_alias=>unistr('USU\00C1RIO-LISTA')
,p_step_title=>unistr('Usu\00E1rio lista')
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
,p_last_updated_by=>'SUPORTE'
,p_last_upd_yyyymmddhh24miss=>'20221208154337'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(8687485943654301)
,p_plug_name=>unistr('Usu\00E1rios')
,p_region_css_classes=>'t-Wizard'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(69725320667463865)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(69640403159463799)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(69812087930463923)
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(82884879084243391762)
,p_plug_name=>'Tabelas'
,p_region_template_options=>'#DEFAULT#:t-Wizard--hideStepsXSmall'
,p_plug_template=>wwv_flow_imp.id(69730137087463867)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ID,',
'       USERNAME,',
'       NOME,',
'       SOBRENOME,',
'       EMAIL,',
'       TIPO,',
'       ''<div class="ng-botao-lista u-color u-info" toggle="tooltip" data-placement="top" title="Editar"><span class="fa fa-edit"><span class="t-Card-initials" ></span></span></div>'' as Link_Editar,',
'       ''<div class="ng-botao-lista u-color u-danger" toggle="tooltip" data-placement="top" title="Excluir"><span class="fa fa-trash"><span class="t-Card-initials" ></span></span></div>'' as Link_Excluir',
'  from ADM_USUARIO'))
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_page_header=>unistr('Apar\00EAncias')
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(82884879185902391762)
,p_name=>unistr('Apar\00EAncias')
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'Nenhuma tabela encontrada!'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'NORTHONN.OLIVEIRA@STAFFINFORMATICA.COM.BR'
,p_internal_uid=>82884879185902391762
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8675497643615720)
,p_db_column_name=>'ID'
,p_display_order=>0
,p_column_identifier=>'B'
,p_column_label=>'ID'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8675828765615720)
,p_db_column_name=>'USERNAME'
,p_display_order=>10
,p_column_identifier=>'AP'
,p_column_label=>unistr('Nome de usu\00E1rio')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8673037963615717)
,p_db_column_name=>'NOME'
,p_display_order=>20
,p_column_identifier=>'AM'
,p_column_label=>'Nome'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8673413405615719)
,p_db_column_name=>'SOBRENOME'
,p_display_order=>30
,p_column_identifier=>'AN'
,p_column_label=>'Sobrenome'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8673897278615719)
,p_db_column_name=>'EMAIL'
,p_display_order=>40
,p_column_identifier=>'AO'
,p_column_label=>'Email'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8674214182615719)
,p_db_column_name=>'LINK_EDITAR'
,p_display_order=>50
,p_column_identifier=>'AI'
,p_column_label=>'&nbsp;'
,p_column_link=>'f?p=&APP_ID.:52:&SESSION.::&DEBUG.:52:P52_ID:#ID#'
,p_column_linktext=>'#LINK_EDITAR#'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8675009206615720)
,p_db_column_name=>'LINK_EXCLUIR'
,p_display_order=>70
,p_column_identifier=>'AK'
,p_column_label=>'&nbsp;'
,p_column_link=>'f?p=&APP_ID.:292:&SESSION.::&DEBUG.:292:P292_ID:#ID#'
,p_column_linktext=>'#LINK_EXCLUIR#'
,p_column_link_attr=>'class="ng-tamanho-coluna-lista"'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_column_alignment=>'CENTER'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(8676209019615721)
,p_db_column_name=>'TIPO'
,p_display_order=>80
,p_column_identifier=>'AQ'
,p_column_label=>'Tipo'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_imp.id(8681334086615754)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(82884623697542173846)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'197968282'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>15
,p_report_columns=>'USERNAME:NOME:TIPO:EMAIL:LINK_EDITAR:LINK_EXCLUIR:'
,p_sort_column_1=>'NM_APARENCIA'
,p_sort_direction_1=>'ASC'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(8676997143615726)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(82884879084243391762)
,p_button_name=>'NEW'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--success'
,p_button_template_id=>wwv_flow_imp.id(69810446314463921)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Novo'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:51:&SESSION.::&DEBUG.:51::'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(8679096024615749)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(82884879084243391762)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(8679517807615749)
,p_event_id=>wwv_flow_imp.id(8679096024615749)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(8680059223615749)
,p_event_id=>wwv_flow_imp.id(8679096024615749)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(82884879084243391762)
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(8677696116615744)
,p_name=>'New Report - Dialog Closed'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(8676997143615726)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(8678191593615748)
,p_event_id=>wwv_flow_imp.id(8677696116615744)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(82884879084243391762)
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(8678633255615749)
,p_event_id=>wwv_flow_imp.id(8677696116615744)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
);
wwv_flow_imp.component_end;
end;
/
